/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparenciaRouteImport } from './routes/transparencia'
import { Route as TramitesRouteImport } from './routes/tramites'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as LegislacionRouteImport } from './routes/legislacion'
import { Route as LaDefensoriaRouteImport } from './routes/la-defensoria'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const TransparenciaRoute = TransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const TramitesRoute = TramitesRouteImport.update({
  id: '/tramites',
  path: '/tramites',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const LegislacionRoute = LegislacionRouteImport.update({
  id: '/legislacion',
  path: '/legislacion',
  getParentRoute: () => rootRouteImport,
} as any)
const LaDefensoriaRoute = LaDefensoriaRouteImport.update({
  id: '/la-defensoria',
  path: '/la-defensoria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/la-defensoria': typeof LaDefensoriaRoute
  '/legislacion': typeof LegislacionRoute
  '/servicios': typeof ServiciosRoute
  '/tramites': typeof TramitesRoute
  '/transparencia': typeof TransparenciaRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/la-defensoria': typeof LaDefensoriaRoute
  '/legislacion': typeof LegislacionRoute
  '/servicios': typeof ServiciosRoute
  '/tramites': typeof TramitesRoute
  '/transparencia': typeof TransparenciaRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/la-defensoria': typeof LaDefensoriaRoute
  '/legislacion': typeof LegislacionRoute
  '/servicios': typeof ServiciosRoute
  '/tramites': typeof TramitesRoute
  '/transparencia': typeof TransparenciaRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/la-defensoria'
    | '/legislacion'
    | '/servicios'
    | '/tramites'
    | '/transparencia'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/la-defensoria'
    | '/legislacion'
    | '/servicios'
    | '/tramites'
    | '/transparencia'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/la-defensoria'
    | '/legislacion'
    | '/servicios'
    | '/tramites'
    | '/transparencia'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LaDefensoriaRoute: typeof LaDefensoriaRoute
  LegislacionRoute: typeof LegislacionRoute
  ServiciosRoute: typeof ServiciosRoute
  TramitesRoute: typeof TramitesRoute
  TransparenciaRoute: typeof TransparenciaRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparencia': {
      id: '/transparencia'
      path: '/transparencia'
      fullPath: '/transparencia'
      preLoaderRoute: typeof TransparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tramites': {
      id: '/tramites'
      path: '/tramites'
      fullPath: '/tramites'
      preLoaderRoute: typeof TramitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legislacion': {
      id: '/legislacion'
      path: '/legislacion'
      fullPath: '/legislacion'
      preLoaderRoute: typeof LegislacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/la-defensoria': {
      id: '/la-defensoria'
      path: '/la-defensoria'
      fullPath: '/la-defensoria'
      preLoaderRoute: typeof LaDefensoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LaDefensoriaRoute: LaDefensoriaRoute,
  LegislacionRoute: LegislacionRoute,
  ServiciosRoute: ServiciosRoute,
  TramitesRoute: TramitesRoute,
  TransparenciaRoute: TransparenciaRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
